Yield
BarnBridge/BarnBridge-YieldFarming pull request #6
Opened 2020-09-13 03:45 UTC by abancu

In Progress
Added Interface for Stake

2020-09-14 08:21 UTC, rizedr commented
[ch150]

2020-09-18 12:24 UTC, kwix commented on test/YieldFarm.test.js
> +
I would add a test with multiple users participating into the pools and also vary the pools.

2020-09-18 13:49 UTC, miladmostavi requested changes

2020-09-18 13:49 UTC, miladmostavi commented on contracts/YieldFarm.sol
> +    address private _barnYCurve;
Rename to _uni_lp please. We'll mostly use USDC_BOND_UNI_LP token.

2020-09-18 13:49 UTC, miladmostavi commented on contracts/YieldFarm.sol
> +    constructor(address barnBridgeAddress, address usdc, address susd, address dai, address barnYCurve, address stakeContract) public {
barnBridgeAddress -> bondTokenAddress

2020-09-18 13:49 UTC, miladmostavi commented on contracts/YieldFarm.sol
> +    constructor(address barnBridgeAddress, address usdc, address susd, address dai, address barnYCurve, address stakeContract) public {
barnYCurve -> should not be part of the constructor -> should be calculated using the deterministic function most probably between _bond and _usdc UNI LP.

```/// https://uniswap.org/docs/v2/smart-contract-integration/getting-pair-addresses/
function genUniAddr(address left, address right) internal pure returns (address) {
    address first = left < right ? left : right;
    address second = left < right ? right : left;
    address pair = address(uint(keccak256(abi.encodePacked(
      hex'ff',
      uniFactory,
      keccak256(abi.encodePacked(first, second)),
      hex'96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f'
    ))));
    return pair;
}

2020-09-18 13:49 UTC, miladmostavi commented on contracts/YieldFarm.sol
> +        // Give user interest
Even in the comments: interest -> reward

2020-09-18 13:49 UTC, miladmostavi commented on contracts/YieldFarm.sol
> +        _barn.transfer(msg.sender, userInterest);
We should `transferFrom(communityVault`

2020-09-18 13:49 UTC, miladmostavi commented on contracts/YieldFarm.sol
> +        uint valueBarnYCurve = _staking.getEpochUserBalance(userAddress, _barnYCurve, epochId);
`valueUniLP`

2020-09-21 16:02 UTC, miladmostavi approved these changes
👍

2020-09-22 05:26 UTC, merged